# Generated by Django 5.0.7 on 2024-07-21 11:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0002_assigned_to_subtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task',
            new_name='TaskItem',
        ),
    ]
