# Generated by Django 5.0.7 on 2024-07-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0003_rename_task_taskitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='status',
        ),
        migrations.AddField(
            model_name='taskitem',
            name='statusCategory',
            field=models.CharField(default='toDo', max_length=25),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='category',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='priority',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
