# Generated by Django 5.0.7 on 2024-07-21 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0004_remove_taskitem_status_taskitem_statuscategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtaskName', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=6)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_task_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='add_task.taskitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
        migrations.AddField(
            model_name='assigned_to',
            name='parent_task_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='add_task.taskitem'),
        ),
    ]
