# Generated by Django 5.0.7 on 2024-07-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0005_subtaskitem_delete_subtask_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskitem',
            old_name='priority',
            new_name='priorityValue',
        ),
    ]
