# Generated by Django 5.0.7 on 2024-07-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0006_rename_priority_taskitem_priorityvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('categoryType', models.CharField(max_length=25)),
            ],
        ),
    ]
