# Generated by Django 5.0.7 on 2024-07-21 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0007_categoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('contactColor', models.CharField(max_length=25)),
                ('parent_task_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='add_task.taskitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Assigned_to',
        ),
    ]
