# Generated by Django 5.0.7 on 2024-07-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0009_assignedcontactitem_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedcontactitem',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='assignedcontactitem',
            old_name='surname',
            new_name='last_name',
        ),
    ]
