# Generated by Django 5.0.7 on 2024-08-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0010_rename_name_assignedcontactitem_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtaskitem',
            name='created_by',
        ),
    ]
